# Docker
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(aacff899-96cc-4c57-a995-787e1a47c8da)'
    appType: 'webApp'
    WebAppName: 'myapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(aacff899-96cc-4c57-a995-787e1a47c8da)'
    appName: 'mlapp'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/DevProRedCodeFlask/MLApp/AppMySQL/Dockerfile'
        tags: |
          $(tag)
